name: Install Git LFS and Clone Repository

on:
  workflow_dispatch:

jobs:
  install-and-clone:
    name: Install Git LFS and Clone Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs
          git lfs install --system

      - name: Clone Hugging Face repository
        run: git clone https://huggingface.co/Salesforce/codet5-small
